/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const WaterEntry = IDL.Record({
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const NightMode = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'muteReminders' : IDL.Bool,
  'enabled' : IDL.Bool,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'timestamp' : Time,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'daysOfWeek' : IDL.Vec(IDL.Bool),
  'time' : IDL.Nat,
  'vibration' : IDL.Bool,
  'enabled' : IDL.Bool,
  'sound' : IDL.Bool,
});
export const WaterDataView = IDL.Record({
  'themeMode' : IDL.Text,
  'dailyGoal' : IDL.Nat,
  'wakeUpTime' : IDL.Opt(IDL.Nat),
  'sleepTime' : IDL.Opt(IDL.Nat),
  'weightHistory' : IDL.Vec(WeightEntry),
  'nightMode' : NightMode,
  'entries' : IDL.Vec(WaterEntry),
  'language' : IDL.Text,
  'reminderMode' : IDL.Text,
  'currentCount' : IDL.Opt(IDL.Nat),
  'units' : IDL.Text,
  'reminders' : IDL.Vec(Reminder),
  'reminderSound' : IDL.Text,
  'missedReminderAlerts' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addReminder' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Bool), IDL.Bool, IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addWeightEntry' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'getAdvancedSettings' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'themeMode' : IDL.Text,
          'wakeUpTime' : IDL.Opt(IDL.Nat),
          'sleepTime' : IDL.Opt(IDL.Nat),
          'language' : IDL.Text,
          'reminderMode' : IDL.Text,
          'units' : IDL.Text,
          'reminderSound' : IDL.Text,
          'missedReminderAlerts' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getCurrentDayIntake' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getDailySummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'goal' : IDL.Nat })],
      ['query'],
    ),
  'getDrinkLog' : IDL.Func([IDL.Nat], [IDL.Vec(WaterEntry)], ['query']),
  'getMonthlySummary' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getNightMode' : IDL.Func([IDL.Nat], [NightMode], ['query']),
  'getProgress' : IDL.Func([IDL.Nat], [WaterDataView], ['query']),
  'getReminders' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
  'getWeeklySummary' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getWeightHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WeightEntry)], ['query']),
  'incrementWaterIntake' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setAdvancedSettings' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'setDailyGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setNightMode' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'toggleReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'updateReminder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Bool),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSleepWakeTimes' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const WaterEntry = IDL.Record({ 'timestamp' : Time, 'amount' : IDL.Nat });
  const NightMode = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'muteReminders' : IDL.Bool,
    'enabled' : IDL.Bool,
  });
  const WeightEntry = IDL.Record({
    'weight' : IDL.Float64,
    'timestamp' : Time,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'daysOfWeek' : IDL.Vec(IDL.Bool),
    'time' : IDL.Nat,
    'vibration' : IDL.Bool,
    'enabled' : IDL.Bool,
    'sound' : IDL.Bool,
  });
  const WaterDataView = IDL.Record({
    'themeMode' : IDL.Text,
    'dailyGoal' : IDL.Nat,
    'wakeUpTime' : IDL.Opt(IDL.Nat),
    'sleepTime' : IDL.Opt(IDL.Nat),
    'weightHistory' : IDL.Vec(WeightEntry),
    'nightMode' : NightMode,
    'entries' : IDL.Vec(WaterEntry),
    'language' : IDL.Text,
    'reminderMode' : IDL.Text,
    'currentCount' : IDL.Opt(IDL.Nat),
    'units' : IDL.Text,
    'reminders' : IDL.Vec(Reminder),
    'reminderSound' : IDL.Text,
    'missedReminderAlerts' : IDL.Bool,
  });
  
  return IDL.Service({
    'addReminder' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Bool), IDL.Bool, IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addWeightEntry' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'getAdvancedSettings' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'themeMode' : IDL.Text,
            'wakeUpTime' : IDL.Opt(IDL.Nat),
            'sleepTime' : IDL.Opt(IDL.Nat),
            'language' : IDL.Text,
            'reminderMode' : IDL.Text,
            'units' : IDL.Text,
            'reminderSound' : IDL.Text,
            'missedReminderAlerts' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getCurrentDayIntake' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getDailySummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'goal' : IDL.Nat })],
        ['query'],
      ),
    'getDrinkLog' : IDL.Func([IDL.Nat], [IDL.Vec(WaterEntry)], ['query']),
    'getMonthlySummary' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getNightMode' : IDL.Func([IDL.Nat], [NightMode], ['query']),
    'getProgress' : IDL.Func([IDL.Nat], [WaterDataView], ['query']),
    'getReminders' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
    'getWeeklySummary' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getWeightHistory' : IDL.Func([IDL.Nat], [IDL.Vec(WeightEntry)], ['query']),
    'incrementWaterIntake' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setAdvancedSettings' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'setDailyGoal' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setNightMode' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'toggleReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'updateReminder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Bool),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSleepWakeTimes' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };