/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NightMode {
  'startTime' : bigint,
  'endTime' : bigint,
  'muteReminders' : boolean,
  'enabled' : boolean,
}
export interface Reminder {
  'id' : bigint,
  'alertType' : string,
  'daysOfWeek' : Array<boolean>,
  'time' : bigint,
  'vibration' : boolean,
  'enabled' : boolean,
  'sound' : boolean,
}
export type Time = bigint;
export interface WaterDataView {
  'themeMode' : string,
  'dailyGoal' : bigint,
  'wakeUpTime' : [] | [bigint],
  'sleepTime' : [] | [bigint],
  'weightHistory' : Array<WeightEntry>,
  'nightMode' : NightMode,
  'entries' : Array<WaterEntry>,
  'language' : string,
  'reminderMode' : string,
  'currentCount' : [] | [bigint],
  'units' : string,
  'reminders' : Array<Reminder>,
  'reminderSound' : string,
  'missedReminderAlerts' : boolean,
}
export interface WaterEntry { 'timestamp' : Time, 'amount' : bigint }
export interface WeightEntry { 'weight' : number, 'timestamp' : Time }
export interface _SERVICE {
  'addReminder' : ActorMethod<
    [bigint, bigint, Array<boolean>, boolean, boolean, string],
    bigint
  >,
  'addWeightEntry' : ActorMethod<[bigint, number], undefined>,
  'getAdvancedSettings' : ActorMethod<
    [bigint],
    {
      'themeMode' : string,
      'wakeUpTime' : [] | [bigint],
      'sleepTime' : [] | [bigint],
      'language' : string,
      'reminderMode' : string,
      'units' : string,
      'reminderSound' : string,
      'missedReminderAlerts' : boolean,
    }
  >,
  'getCurrentDayIntake' : ActorMethod<[bigint], bigint>,
  'getDailySummary' : ActorMethod<
    [bigint],
    { 'total' : bigint, 'goal' : bigint }
  >,
  'getDrinkLog' : ActorMethod<[bigint], Array<WaterEntry>>,
  'getMonthlySummary' : ActorMethod<[bigint], bigint>,
  'getNightMode' : ActorMethod<[bigint], NightMode>,
  'getProgress' : ActorMethod<[bigint], WaterDataView>,
  'getReminders' : ActorMethod<[bigint], Array<Reminder>>,
  'getWeeklySummary' : ActorMethod<[bigint], bigint>,
  'getWeightHistory' : ActorMethod<[bigint], Array<WeightEntry>>,
  'incrementWaterIntake' : ActorMethod<[bigint, bigint], undefined>,
  'setAdvancedSettings' : ActorMethod<
    [
      bigint,
      string,
      string,
      boolean,
      string,
      string,
      string,
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'setDailyGoal' : ActorMethod<[bigint, bigint], undefined>,
  'setNightMode' : ActorMethod<
    [bigint, boolean, bigint, bigint, boolean],
    undefined
  >,
  'toggleReminder' : ActorMethod<[bigint, bigint, boolean], undefined>,
  'updateReminder' : ActorMethod<
    [bigint, bigint, bigint, Array<boolean>, boolean, boolean, string],
    undefined
  >,
  'updateSleepWakeTimes' : ActorMethod<
    [bigint, [] | [bigint], [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];