/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NightMode {
    startTime: bigint;
    endTime: bigint;
    muteReminders: boolean;
    enabled: boolean;
}
export interface WaterEntry {
    timestamp: Time;
    amount: bigint;
}
export type Time = bigint;
export interface WeightEntry {
    weight: number;
    timestamp: Time;
}
export interface WaterDataView {
    themeMode: string;
    dailyGoal: bigint;
    wakeUpTime?: bigint;
    sleepTime?: bigint;
    weightHistory: Array<WeightEntry>;
    nightMode: NightMode;
    entries: Array<WaterEntry>;
    language: string;
    reminderMode: string;
    currentCount?: bigint;
    units: string;
    reminders: Array<Reminder>;
    reminderSound: string;
    missedReminderAlerts: boolean;
}
export interface Reminder {
    id: bigint;
    alertType: string;
    daysOfWeek: Array<boolean>;
    time: bigint;
    vibration: boolean;
    enabled: boolean;
    sound: boolean;
}
export interface backendInterface {
    addReminder(userId: bigint, time: bigint, daysOfWeek: Array<boolean>, sound: boolean, vibration: boolean, alertType: string): Promise<bigint>;
    addWeightEntry(userId: bigint, weight: number): Promise<void>;
    getAdvancedSettings(userId: bigint): Promise<{
        themeMode: string;
        wakeUpTime?: bigint;
        sleepTime?: bigint;
        language: string;
        reminderMode: string;
        units: string;
        reminderSound: string;
        missedReminderAlerts: boolean;
    }>;
    getCurrentDayIntake(userId: bigint): Promise<bigint>;
    getDailySummary(userId: bigint): Promise<{
        total: bigint;
        goal: bigint;
    }>;
    getDrinkLog(userId: bigint): Promise<Array<WaterEntry>>;
    getMonthlySummary(userId: bigint): Promise<bigint>;
    getNightMode(userId: bigint): Promise<NightMode>;
    getProgress(userId: bigint): Promise<WaterDataView>;
    getReminders(userId: bigint): Promise<Array<Reminder>>;
    getWeeklySummary(userId: bigint): Promise<bigint>;
    getWeightHistory(userId: bigint): Promise<Array<WeightEntry>>;
    incrementWaterIntake(userId: bigint, amount: bigint): Promise<void>;
    setAdvancedSettings(userId: bigint, reminderSound: string, reminderMode: string, missedReminderAlerts: boolean, units: string, themeMode: string, language: string, wakeUpTime: bigint | null, sleepTime: bigint | null): Promise<void>;
    setDailyGoal(userId: bigint, goal: bigint): Promise<void>;
    setNightMode(userId: bigint, enabled: boolean, startTime: bigint, endTime: bigint, muteReminders: boolean): Promise<void>;
    toggleReminder(userId: bigint, reminderId: bigint, enabled: boolean): Promise<void>;
    updateReminder(userId: bigint, reminderId: bigint, time: bigint, daysOfWeek: Array<boolean>, sound: boolean, vibration: boolean, alertType: string): Promise<void>;
    updateSleepWakeTimes(userId: bigint, wakeUpTime: bigint | null, sleepTime: bigint | null): Promise<void>;
}
import type { NightMode as _NightMode, Reminder as _Reminder, WaterDataView as _WaterDataView, WaterEntry as _WaterEntry, WeightEntry as _WeightEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReminder(arg0: bigint, arg1: bigint, arg2: Array<boolean>, arg3: boolean, arg4: boolean, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addWeightEntry(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, arg1);
            return result;
        }
    }
    async getAdvancedSettings(arg0: bigint): Promise<{
        themeMode: string;
        wakeUpTime?: bigint;
        sleepTime?: bigint;
        language: string;
        reminderMode: string;
        units: string;
        reminderSound: string;
        missedReminderAlerts: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancedSettings(arg0);
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancedSettings(arg0);
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentDayIntake(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDayIntake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDayIntake(arg0);
            return result;
        }
    }
    async getDailySummary(arg0: bigint): Promise<{
        total: bigint;
        goal: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return result;
        }
    }
    async getDrinkLog(arg0: bigint): Promise<Array<WaterEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrinkLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrinkLog(arg0);
            return result;
        }
    }
    async getMonthlySummary(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0);
            return result;
        }
    }
    async getNightMode(arg0: bigint): Promise<NightMode> {
        if (this.processError) {
            try {
                const result = await this.actor.getNightMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNightMode(arg0);
            return result;
        }
    }
    async getProgress(arg0: bigint): Promise<WaterDataView> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0);
                return from_candid_WaterDataView_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0);
            return from_candid_WaterDataView_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(arg0: bigint): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders(arg0);
            return result;
        }
    }
    async getWeeklySummary(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklySummary(arg0);
            return result;
        }
    }
    async getWeightHistory(arg0: bigint): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightHistory(arg0);
            return result;
        }
    }
    async incrementWaterIntake(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementWaterIntake(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementWaterIntake(arg0, arg1);
            return result;
        }
    }
    async setAdvancedSettings(arg0: bigint, arg1: string, arg2: string, arg3: boolean, arg4: string, arg5: string, arg6: string, arg7: bigint | null, arg8: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdvancedSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdvancedSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async setDailyGoal(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyGoal(arg0, arg1);
            return result;
        }
    }
    async setNightMode(arg0: bigint, arg1: boolean, arg2: bigint, arg3: bigint, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNightMode(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNightMode(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async toggleReminder(arg0: bigint, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async updateReminder(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Array<boolean>, arg4: boolean, arg5: boolean, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSleepWakeTimes(arg0: bigint, arg1: bigint | null, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSleepWakeTimes(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSleepWakeTimes(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_WaterDataView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WaterDataView): WaterDataView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    themeMode: string;
    wakeUpTime: [] | [bigint];
    sleepTime: [] | [bigint];
    language: string;
    reminderMode: string;
    units: string;
    reminderSound: string;
    missedReminderAlerts: boolean;
}): {
    themeMode: string;
    wakeUpTime?: bigint;
    sleepTime?: bigint;
    language: string;
    reminderMode: string;
    units: string;
    reminderSound: string;
    missedReminderAlerts: boolean;
} {
    return {
        themeMode: value.themeMode,
        wakeUpTime: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.wakeUpTime)),
        sleepTime: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.sleepTime)),
        language: value.language,
        reminderMode: value.reminderMode,
        units: value.units,
        reminderSound: value.reminderSound,
        missedReminderAlerts: value.missedReminderAlerts
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    themeMode: string;
    dailyGoal: bigint;
    wakeUpTime: [] | [bigint];
    sleepTime: [] | [bigint];
    weightHistory: Array<_WeightEntry>;
    nightMode: _NightMode;
    entries: Array<_WaterEntry>;
    language: string;
    reminderMode: string;
    currentCount: [] | [bigint];
    units: string;
    reminders: Array<_Reminder>;
    reminderSound: string;
    missedReminderAlerts: boolean;
}): {
    themeMode: string;
    dailyGoal: bigint;
    wakeUpTime?: bigint;
    sleepTime?: bigint;
    weightHistory: Array<WeightEntry>;
    nightMode: NightMode;
    entries: Array<WaterEntry>;
    language: string;
    reminderMode: string;
    currentCount?: bigint;
    units: string;
    reminders: Array<Reminder>;
    reminderSound: string;
    missedReminderAlerts: boolean;
} {
    return {
        themeMode: value.themeMode,
        dailyGoal: value.dailyGoal,
        wakeUpTime: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.wakeUpTime)),
        sleepTime: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.sleepTime)),
        weightHistory: value.weightHistory,
        nightMode: value.nightMode,
        entries: value.entries,
        language: value.language,
        reminderMode: value.reminderMode,
        currentCount: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.currentCount)),
        units: value.units,
        reminders: value.reminders,
        reminderSound: value.reminderSound,
        missedReminderAlerts: value.missedReminderAlerts
    };
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
